In [1]:
import pickle
import bz2
sfile1 = bz2.BZ2File('All Model', 'r')
models=pickle.load(sfile1)
sfile2 = bz2.BZ2File('All Vector', 'r')
vectorizer=pickle.load(sfile2)
cas=input("Enter Case Study")

Enter Case StudyA person was attacked by an armed assailant in a dark alley. In an act of self-defense, the victim fought back and managed to disarm the attacker. However, during the struggle, the assailant was killed. In this case, it can be argued that the victim acted in self-defense to protect their life, and the homicide may not be classified as murder.

In [2]:
import pandas as pd
df=pd.DataFrame({"case study":[cas]})
df

                                          case study
0  A person was attacked by an armed assailant in...

In [3]:
import nltk 
def remove_stopwords(text):
    stopwords=nltk.corpus.stopwords.words('english')
    clean_text=' '.join([word for word in text.split() if word not in stopwords])
    return clean_text

from nltk.stem.porter import PorterStemmer
def cleanup_data(df):
    # remove handle
    df['clean'] = df["case study"].str.replace("@", "") 
    # remove links
    df['clean'] = df['clean'].str.replace(r"http\S+", "") 
    # remove punctuations and special characters
    df['clean'] = df['clean'].str.replace("[^a-zA-Z]", " ") 
    # remove stop words
    df['clean'] = df['clean'].apply(lambda text : remove_stopwords(text.lower()))
    # split text and tokenize
    df['clean'] = df['clean'].apply(lambda x: x.split())
    # let's apply stemmer
    stemmer = PorterStemmer()
    df['clean'] = df['clean'].apply(lambda x: [stemmer.stem(i) for i in x])
    # stitch back words
    df['clean'] = df['clean'].apply(lambda x: ' '.join([w for w in x]))
    # remove small words
    df['clean'] = df['clean'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
cleanup_data(df)
df

C:\Users\Dhairya Vyas\AppData\Local\Temp\ipykernel_20348\3226446464.py:12: FutureWarning: The default value of regex will change from True to False in a future version.
  df['clean'] = df['clean'].str.replace(r"http\S+", "")
C:\Users\Dhairya Vyas\AppData\Local\Temp\ipykernel_20348\3226446464.py:14: FutureWarning: The default value of regex will change from True to False in a future version.
  df['clean'] = df['clean'].str.replace("[^a-zA-Z]", " ")

,case study,clean
0,A person was attacked by an armed assailant in...,person attack assail dark alley self defens vi...

In [4]:
df["clean"][0]

'person attack assail dark alley self defens victim fought back manag disarm attack howev struggl assail kill case argu victim self defens protect life homicid classifi murder'

In [5]:
feature=vectorizer.transform([df["clean"][0]])
feature.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [6]:
names = ["K-Nearest Neighbors", "Liner SVM",
         "Decision Tree", "Random Forest",
         "ExtraTreesClassifier"]
for i in range(0,len(names)):
    print(names[i])
    print(models[i].predict(feature))

K-Nearest Neighbors
['300']
Liner SVM
['300']
Decision Tree
['359']
Random Forest
['300']
ExtraTreesClassifier
['300']

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)